//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 30/05/2012 7:33:04 PM
namespace FinanceDataLayer
{
    
    /// <summary>
    /// There are no comments for FinanceAuditSyncEntities in the schema.
    /// </summary>
    public partial class FinanceAuditSyncEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new FinanceAuditSyncEntities object using the connection string found in the 'FinanceAuditSyncEntities' section of the application configuration file.
        /// </summary>
        public FinanceAuditSyncEntities() : 
                base("name=FinanceAuditSyncEntities", "FinanceAuditSyncEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new FinanceAuditSyncEntities object.
        /// </summary>
        public FinanceAuditSyncEntities(string connectionString) : 
                base(connectionString, "FinanceAuditSyncEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new FinanceAuditSyncEntities object.
        /// </summary>
        public FinanceAuditSyncEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "FinanceAuditSyncEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for csuAuditDebtorSyncs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<csuAuditDebtorSync> csuAuditDebtorSyncs
        {
            get
            {
                if ((this._csuAuditDebtorSyncs == null))
                {
                    this._csuAuditDebtorSyncs = base.CreateQuery<csuAuditDebtorSync>("[csuAuditDebtorSyncs]");
                }
                return this._csuAuditDebtorSyncs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<csuAuditDebtorSync> _csuAuditDebtorSyncs;
        /// <summary>
        /// There are no comments for csuAuditTransSyncs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<csuAuditTransSync> csuAuditTransSyncs
        {
            get
            {
                if ((this._csuAuditTransSyncs == null))
                {
                    this._csuAuditTransSyncs = base.CreateQuery<csuAuditTransSync>("[csuAuditTransSyncs]");
                }
                return this._csuAuditTransSyncs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<csuAuditTransSync> _csuAuditTransSyncs;
        /// <summary>
        /// There are no comments for csuAuditDebtorSyncs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTocsuAuditDebtorSyncs(csuAuditDebtorSync csuAuditDebtorSync)
        {
            base.AddObject("csuAuditDebtorSyncs", csuAuditDebtorSync);
        }
        /// <summary>
        /// There are no comments for csuAuditTransSyncs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTocsuAuditTransSyncs(csuAuditTransSync csuAuditTransSync)
        {
            base.AddObject("csuAuditTransSyncs", csuAuditTransSync);
        }
    }
    /// <summary>
    /// There are no comments for FinanceAuditSyncModel.csuAuditDebtorSync in the schema.
    /// </summary>
    /// <KeyProperties>
    /// iAuditId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FinanceAuditSyncModel", Name="csuAuditDebtorSync")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class csuAuditDebtorSync : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new csuAuditDebtorSync object.
        /// </summary>
        /// <param name="iAuditId">Initial value of iAuditId.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static csuAuditDebtorSync CreatecsuAuditDebtorSync(int iAuditId)
        {
            csuAuditDebtorSync csuAuditDebtorSync = new csuAuditDebtorSync();
            csuAuditDebtorSync.iAuditId = iAuditId;
            return csuAuditDebtorSync;
        }
        /// <summary>
        /// There are no comments for property iAuditId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int iAuditId
        {
            get
            {
                return this._iAuditId;
            }
            set
            {
                this.OniAuditIdChanging(value);
                this.ReportPropertyChanging("iAuditId");
                this._iAuditId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iAuditId");
                this.OniAuditIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _iAuditId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniAuditIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniAuditIdChanged();
        /// <summary>
        /// There are no comments for property vchUsername in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchUsername
        {
            get
            {
                return this._vchUsername;
            }
            set
            {
                this.OnvchUsernameChanging(value);
                this.ReportPropertyChanging("vchUsername");
                this._vchUsername = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchUsername");
                this.OnvchUsernameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchUsername;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchUsernameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchUsernameChanged();
        /// <summary>
        /// There are no comments for property dtChangeDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> dtChangeDate
        {
            get
            {
                return this._dtChangeDate;
            }
            set
            {
                this.OndtChangeDateChanging(value);
                this.ReportPropertyChanging("dtChangeDate");
                this._dtChangeDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dtChangeDate");
                this.OndtChangeDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _dtChangeDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtChangeDateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtChangeDateChanged();
        /// <summary>
        /// There are no comments for property vchAction in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchAction
        {
            get
            {
                return this._vchAction;
            }
            set
            {
                this.OnvchActionChanging(value);
                this.ReportPropertyChanging("vchAction");
                this._vchAction = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchAction");
                this.OnvchActionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchAction;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchActionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchActionChanged();
        /// <summary>
        /// There are no comments for property MemberId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> MemberId
        {
            get
            {
                return this._MemberId;
            }
            set
            {
                this.OnMemberIdChanging(value);
                this.ReportPropertyChanging("MemberId");
                this._MemberId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MemberId");
                this.OnMemberIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _MemberId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMemberIdChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMemberIdChanged();
        /// <summary>
        /// There are no comments for property vchType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchType
        {
            get
            {
                return this._vchType;
            }
            set
            {
                this.OnvchTypeChanging(value);
                this.ReportPropertyChanging("vchType");
                this._vchType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchType");
                this.OnvchTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchType;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchTypeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchTypeChanged();
        /// <summary>
        /// There are no comments for property vchReason in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchReason
        {
            get
            {
                return this._vchReason;
            }
            set
            {
                this.OnvchReasonChanging(value);
                this.ReportPropertyChanging("vchReason");
                this._vchReason = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchReason");
                this.OnvchReasonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchReason;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchReasonChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchReasonChanged();
    }
    /// <summary>
    /// There are no comments for FinanceAuditSyncModel.csuAuditTransSync in the schema.
    /// </summary>
    /// <KeyProperties>
    /// iAuditId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FinanceAuditSyncModel", Name="csuAuditTransSync")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class csuAuditTransSync : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new csuAuditTransSync object.
        /// </summary>
        /// <param name="iAuditId">Initial value of iAuditId.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static csuAuditTransSync CreatecsuAuditTransSync(int iAuditId)
        {
            csuAuditTransSync csuAuditTransSync = new csuAuditTransSync();
            csuAuditTransSync.iAuditId = iAuditId;
            return csuAuditTransSync;
        }
        /// <summary>
        /// There are no comments for property iAuditId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int iAuditId
        {
            get
            {
                return this._iAuditId;
            }
            set
            {
                this.OniAuditIdChanging(value);
                this.ReportPropertyChanging("iAuditId");
                this._iAuditId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iAuditId");
                this.OniAuditIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _iAuditId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniAuditIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniAuditIdChanged();
        /// <summary>
        /// There are no comments for property documentId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string documentId
        {
            get
            {
                return this._documentId;
            }
            set
            {
                this.OndocumentIdChanging(value);
                this.ReportPropertyChanging("documentId");
                this._documentId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("documentId");
                this.OndocumentIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _documentId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndocumentIdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndocumentIdChanged();
        /// <summary>
        /// There are no comments for property vchAction in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchAction
        {
            get
            {
                return this._vchAction;
            }
            set
            {
                this.OnvchActionChanging(value);
                this.ReportPropertyChanging("vchAction");
                this._vchAction = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchAction");
                this.OnvchActionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchAction;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchActionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchActionChanged();
        /// <summary>
        /// There are no comments for property vchSystem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchSystem
        {
            get
            {
                return this._vchSystem;
            }
            set
            {
                this.OnvchSystemChanging(value);
                this.ReportPropertyChanging("vchSystem");
                this._vchSystem = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchSystem");
                this.OnvchSystemChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchSystem;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchSystemChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchSystemChanged();
        /// <summary>
        /// There are no comments for property vchReason in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string vchReason
        {
            get
            {
                return this._vchReason;
            }
            set
            {
                this.OnvchReasonChanging(value);
                this.ReportPropertyChanging("vchReason");
                this._vchReason = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("vchReason");
                this.OnvchReasonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _vchReason;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchReasonChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnvchReasonChanged();
        /// <summary>
        /// There are no comments for property chupdateBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string chupdateBy
        {
            get
            {
                return this._chupdateBy;
            }
            set
            {
                this.OnchupdateByChanging(value);
                this.ReportPropertyChanging("chupdateBy");
                this._chupdateBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("chupdateBy");
                this.OnchupdateByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _chupdateBy;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnchupdateByChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnchupdateByChanged();
        /// <summary>
        /// There are no comments for property dtChangeDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> dtChangeDate
        {
            get
            {
                return this._dtChangeDate;
            }
            set
            {
                this.OndtChangeDateChanging(value);
                this.ReportPropertyChanging("dtChangeDate");
                this._dtChangeDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dtChangeDate");
                this.OndtChangeDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _dtChangeDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtChangeDateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtChangeDateChanged();
    }
}
